[package]
name = "extract_ebub_inkbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
epub = "1.2.2"
env_logger = "0.9.0"
log = "0.4.0"
tinyjson = "2"
